language: node_js
node_js:
    - "12"
env:
    - DOMAIN=worldover.dark-sides.com
script:
    - npm run lint
    - npm run build
    - echo $DOMAIN > dist/worldover/CNAME
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/worldover
    on:
        branch: master
